version: '3'
services:
  smtp:
    image: namshi/smtp
    container_name: lm_smtp
    ports:
      - 25
    environment:
      - GMAIL_USER=${SMTP_GMAIL_USER}
      - GMAIL_PASSWORD=${SMTP_GMAIL_USER_PASSWORD}

  login-monitor:
    image: francois/login-monitor
    container_name: login-monitor
    links:
      - smtp:smtp
    volumes:
      - /var/log/auth.log:/root/log/auth.log
      - /home/fanch/login-monitor/authorized_ips.list:/root/authorized_ips.list
      - /home/fanch/login-monitor/already_sent.list:/root/already_sent.list
    environment:
      - SMTP_HOST=smtp
      - EMAIL_ADDR=${DEST_EMAIL_ADDRESS}
    command: ["/root/wait-for-it.sh", "smtp:25", "--", "/root/login_monitor.sh"]
